blade_brew_formulae:
  - ansible
  - kubectl
  - helm
  - k9s
  - jq
  - yq
  - gh

blade_brew_casks: []

blade_ollama_models:
  - "qwen3:72b"
  - "deepseek-r1:70b"

blade_ollama_models_dir: "/Volumes/Data/ollama/models"
